
version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_jaffle_shop__customer')
              field: customer_id
      - name: first_name 
        tests:
          -   not_null
      - name: last_name 
        tests:
          - not_null


