
version: 2

models:
  - name: customer_orders 
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
  - name: fct_customer_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null 
      - name: order_status
        tests:
          - not_null
      - name: customer_first_name
        tests:
          - not_null
      - name: customer_last_name
        tests:
          - not_null


