
version: 2
models: 
    - name: int_orders
      columns: 
        - name: order_id
          tests:
            - unique
            - not_null
        - name: customer_id
          tests:
            - not_null
            - relationships:
                to: ref('stg_jaffle_shop__orders')
                field: customer_id
        - name: order_status
          tests: 
            - not_null
            

